### ISSUE TITLE
СУБД ДЗ 1

### ISSUE THREAD

**Issue by ns-roxer** [go-park-mail-ru/2024_1_ResCogitans#17]
1) https://github.com/go-park-mail-ru/2024_1_ResCogitans/blob/database/db/migrations/20240401145225_create_and_insert_tables.sql#L8
Города точно не должны быть уникальны?

2) user, image и profile стоит переимновать, чтобы не бороться с коллизиями имен с зарезервированными словами. Это вас убережет от ошибок с кавычками. Самое простое - добавить суффикс `_data`

3) В таблицах:
sight
image
journey
journey_sight
feedback

явно не хватает уникальных ключей. Сейчас в них можно создавать кортежи, которые будут отличаться ТОЛЬКО значениями суррогатного ключа - а это не имеет смысла с точки зрения бизнес-логики

**Comment by MrDzhofik** [comment]
Пришлось оставить ветку database и переключиться на ветку [improve_journey_exg0rd](https://github.com/go-park-mail-ru/2024_1_ResCogitans/tree/improve_journey_exg0rd)

1. Встречаются города с одинаковыми названиями, которые расположены в разных регионах. У них будут разные ID, по которым в будущем мы будем фильтровать, чтобы получить достопримечательности одного города. [Источник](https://geogoroda.ru/stati/goroda-rossii-s-odinakovymi-nazvaniyami)
2. Поменял названия таблиц, чтобы не было ошибок с кавычками
3. Добавил уникальные ключи в таблицы:
Sight - не возможно добавить достопримечательность с одним и тем же названием и городом
Image - путь до картинки уникален
Journey - название поездки уникально
Journey_Sight - Нельзя добавить два раза одну и ту жу достопримечательность в поездку
Feedback - пользователь может оставлять только один комментарий под достопримечательностью

**Comment by ns-roxer** [comment]
3. 
> Feedback - пользователь может оставлять только один комментарий под достопримечательностью
https://github.com/go-park-mail-ru/2024_1_ResCogitans/blob/improve_journey_exg0rd/db/migrations/20240401145225_create_and_insert_tables.sql#L60-L66 - не вижу в описании таблицы этого условия

1.
> Встречаются города с одинаковыми названиями, которые расположены в разных регионах

Справедливо

> У них будут разные ID

Очень неинформативно. Из предыдущего утверждения четко следует, что у города должен быть регион, и пара атрибутов (название города + название региона) будут образовывать уникальный ключ.

Если вам регионы сами по себе в приложении не нужны, то заведите их просто текстовым атрибутом в таблице городов. Но если хотите по-правильному, то сделайте еще одну-таблицу справочник, на записи которой будут ссылаться города.

**Comment by MrDzhofik** [comment]
Добавил регион в таблицу городов и ограничение на отзыв, а также изменил ERD-диаграмму

**Comment by ns-roxer** [comment]
Вот почти-почти.
https://github.com/go-park-mail-ru/2024_1_ResCogitans/blob/database/db/migrations/20240401145225_create_and_insert_tables.sql#L8

Но вы сейчас связали города со странами через достопримечательности. И получается, что проблема дублирующихся городов в таблице city никуда не делась.

Вот же я писал:

> у города должен быть регион, и пара атрибутов (название города + название региона) будут образовывать уникальный ключ.

Достопримечательность должна быть связана со страной через город

**Comment by MrDzhofik** [comment]
Связал город со страной, теперь в достопримечательности указывается только город, а оттуда уже страна подтягивается. Также изменил ERD-диаграмму

**Comment by ns-roxer** [comment]
где? Не вижу новых коммитов в ветке database

**Comment by MrDzhofik** [comment]
Мы перешли в ветку improve_journey_exg0rd

**Comment by ns-roxer** [comment]
Простите, а я как должен был догадаться?!

**Comment by MrDzhofik** [comment]
Я в прошлый раз об этом упомянул, в этот раз забыл...

**Comment by ns-roxer** [comment]
так, зачет поставлю, но есть минорные пожелания:
https://github.com/go-park-mail-ru/2024_1_ResCogitans/blob/improve_journey_exg0rd/db/migrations/20240401145225_create_and_insert_tables.sql
поправить форматирование - местами отступы у атрибутов разные

избавиться в названиях от зарезервированных слов, которые приходится брать в кавычки

**Comment by MrDzhofik** [comment]
Хорошо, спасибо!
